apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

resources:
- namespace.yaml
- ../base

patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: pacordonnier/pacordonnierdemocicd
  newTag: "1.2"
