apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

resources:
- namespace.yaml
- ../base

patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: pacordonnier/pacordonnierdemocicd
  newTag: f6f60879913284d2df6792e6ef6d4481ef1c8fa3
