apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
Namespace: prod
bases:
- ../base

resources:
- namespace.yaml

patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: pacordonnier/pacordonnierdemocicd
  newTag: "1.1"
